package tamagochi;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.layout.Pane;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Patri
 */
public class TamagoView extends javax.swing.JFrame {

    Creature kiki;

    /**
     * Creates new form TamagoView
     */
    public TamagoView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        texte = new javax.swing.JTextPane();
        manger = new javax.swing.JButton();
        boire = new javax.swing.JButton();
        dormir = new javax.swing.JButton();
        sport = new javax.swing.JButton();
        jLabelFaim = new javax.swing.JLabel();
        jLabelPoid = new javax.swing.JLabel();
        jLabelFatigue = new javax.swing.JLabel();
        jLabelSoif = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        afficheSoif = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        afficheFaim = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        afficheFatigue = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        affichePoid = new javax.swing.JTextPane();
        start = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(texte);

        manger.setText("Manger");
        manger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mangerActionPerformed(evt);
            }
        });

        boire.setText("Boire");
        boire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boireActionPerformed(evt);
            }
        });

        dormir.setText("Dormir");
        dormir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dormirActionPerformed(evt);
            }
        });

        sport.setText("sport");
        sport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sportActionPerformed(evt);
            }
        });

        jLabelFaim.setText("Faim");

        jLabelPoid.setText("Poid");

        jLabelFatigue.setText("Fatigue");

        jLabelSoif.setText("Soif");

        jScrollPane2.setViewportView(afficheSoif);

        jScrollPane3.setViewportView(afficheFaim);

        jScrollPane4.setViewportView(afficheFatigue);

        jScrollPane5.setViewportView(affichePoid);

        start.setText("Démarrer");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(manger)
                        .addGap(158, 158, 158)
                        .addComponent(boire)
                        .addGap(157, 157, 157)
                        .addComponent(dormir)
                        .addGap(160, 160, 160)
                        .addComponent(sport))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1001, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabelFatigue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelSoif, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelFaim, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelPoid, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(68, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 530, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manger)
                    .addComponent(boire)
                    .addComponent(dormir)
                    .addComponent(sport)
                    .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFaim, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelSoif, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFatigue, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPoid, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mangerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mangerActionPerformed

        kiki.mange();
        texte.setText("hummmf grrrrr!! (Kiki à bien mangé il n'a plus faim)");
        majAffiche();
        if (!kiki.checkAlive()) {
            texte.setText(kiki.causeDc());
            kiki = null;
            majAffiche();
        }


    }//GEN-LAST:event_mangerActionPerformed

    private void dormirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dormirActionPerformed

        kiki.dort();
        texte.setText("hummmf grrrrr!! (Kiki à bien dormi il est totalement reposé)");
        majAffiche();
        if (!kiki.checkAlive()) {
            texte.setText(kiki.causeDc());
            kiki = null;
            majAffiche();
        }
    }//GEN-LAST:event_dormirActionPerformed

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed

        kiki = new Creature(10, 10, 10, 10, 10, true);
        texte.setText("Bienvenue dans Tamagochi v 2.0 !    Kiki est impatient que vous vous occupiez de lui !");
        afficheFaim.setText(kiki.getFaimAffiche());
        afficheSoif.setText(kiki.getSoifAffiche());
        afficheFatigue.setText(kiki.getEnergieAffiche());
        affichePoid.setText(kiki.getPoidAffiche());
        
    }//GEN-LAST:event_startActionPerformed

    private void sportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sportActionPerformed

        if (kiki != null) {
            kiki.sport();
            texte.setText("hummmf grrrrr!! (Kiki c'est bien dépensé, il a perdu du poid)");
            majAffiche();
            if (!kiki.checkAlive()) {
                texte.setText(kiki.causeDc());
                kiki = null;
                majAffiche();
            }
        }
    }//GEN-LAST:event_sportActionPerformed

    private void boireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boireActionPerformed
        kiki.bois();
        texte.setText("hummmf grrrrr!! (Kiki à bien bu il n'a plus soif)");
        majAffiche();
        if (!kiki.checkAlive()) {
            texte.setText(kiki.causeDc());
            kiki = null;
            majAffiche();
        }
    }//GEN-LAST:event_boireActionPerformed

    private void majAffiche() {
        if (kiki != null) {
            afficheFaim.setText(kiki.getFaimAffiche());
            afficheSoif.setText(kiki.getSoifAffiche());
            afficheFatigue.setText(kiki.getEnergieAffiche());
            affichePoid.setText(kiki.getPoidAffiche());
        } else {
            afficheFaim.setText("relancez une partie");
            afficheSoif.setText("relancez une partie");
            afficheFatigue.setText("relancez une partie");
            affichePoid.setText("relancez une partie");
        }
    }

   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TamagoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TamagoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TamagoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TamagoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TamagoView().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane afficheFaim;
    private javax.swing.JTextPane afficheFatigue;
    private javax.swing.JTextPane affichePoid;
    private javax.swing.JTextPane afficheSoif;
    private javax.swing.JButton boire;
    private javax.swing.JButton dormir;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabelFaim;
    private javax.swing.JLabel jLabelFatigue;
    private javax.swing.JLabel jLabelPoid;
    private javax.swing.JLabel jLabelSoif;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton manger;
    private javax.swing.JButton sport;
    private javax.swing.JButton start;
    private javax.swing.JTextPane texte;
    // End of variables declaration//GEN-END:variables
}
